### ISSUE TITLE
Read AMQP URL from env var

### ISSUE THREAD

**Issue by dkarlovi** [skolodyazhnyy/amqp-cgi-bridge#2]
Would facilitate 12 factor and deploying into Docker / K8s.

**Comment by skolodyazhnyy** [comment]
I've missed your request, sorry about this. You can definitely deploy it using containers, I would even say it was meant to be this way. You can use a pod with two containers, one with this app and another one with PHPFPM+PHP code. You can use a config map to deploy configuration file.

Unfortunately there is no support for env vars at the moment nor there is docker image, I would really welcome the contribution :)

**Comment by skolodyazhnyy** [comment]
I'm gonna closed it since you probably forgot all about it, but feel free to reopen.
